trigger:
- main

variables:
- group: BuildVariables
- group: InsiderBuilds

pool: Default

resources:
  repositories:
    - repository: Template
      type: github
      name: gunnargestsson/bcbuildtemplate
      ref: master

extends:
  template: /.azureDevOps/CI.yml@Template
  parameters:
    version: "nextminor"
    appVersion: "17.2"

